"""目标域：Goal Agent（澄清状态机）与能力模型生成。"""

from .agent import (
    CLARIFICATION_SYSTEM,
    MAX_ROUNDS,
    ClarificationLimitReached,
    ClarificationTurn,
    GoalAgent,
    GoalElements,
    GoalStateError,
    GoalTurnResult,
    require_confirmed_goal,
)
from .capability_model import (
    CAPABILITY_SYSTEM,
    MAX_DEPTH,
    MIN_CAPABILITIES,
    MIN_DOMAINS,
    UNVERIFIED_MARK,
    CapabilityModelError,
    CapabilityModelGenerator,
    CapabilityNode,
    CapabilityTree,
    CapabilityTreeShapeError,
    GenerationReport,
    validate_shape,
)

__all__ = [
    "CAPABILITY_SYSTEM",
    "CLARIFICATION_SYSTEM",
    "MAX_DEPTH",
    "MAX_ROUNDS",
    "MIN_CAPABILITIES",
    "MIN_DOMAINS",
    "UNVERIFIED_MARK",
    "CapabilityModelError",
    "CapabilityModelGenerator",
    "CapabilityNode",
    "CapabilityTree",
    "CapabilityTreeShapeError",
    "ClarificationLimitReached",
    "ClarificationTurn",
    "GenerationReport",
    "GoalAgent",
    "GoalElements",
    "GoalStateError",
    "GoalTurnResult",
    "require_confirmed_goal",
    "validate_shape",
]
